Search.appendIndex(
    [
                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger",
            "name": "Logger",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#method_init"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#method_log"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AcollectDebugInformation\u0028\u0029",
            "name": "collectDebugInformation",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#method_collectDebugInformation"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AprepareMessage\u0028\u0029",
            "name": "prepareMessage",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#method_prepareMessage"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AEMERGENCY",
            "name": "EMERGENCY",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_EMERGENCY"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AALERT",
            "name": "ALERT",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_ALERT"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003ACRITICAL",
            "name": "CRITICAL",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_CRITICAL"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AERROR",
            "name": "ERROR",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_ERROR"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AWARNING",
            "name": "WARNING",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_WARNING"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003ANOTICE",
            "name": "NOTICE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_NOTICE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003AINFO",
            "name": "INFO",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_INFO"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003ADEBUG",
            "name": "DEBUG",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#constant_DEBUG"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Logger\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Logger.html#property_logger"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map",
            "name": "Map",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003Asetup\u0028\u0029",
            "name": "setup",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_setup"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003Amain\u0028\u0029",
            "name": "main",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_main"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003AscanPath\u0028\u0029",
            "name": "scanPath",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_scanPath"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003AgetBasePathFromSpec\u0028\u0029",
            "name": "getBasePathFromSpec",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_getBasePathFromSpec"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003AgetNamespaceFromSpec\u0028\u0029",
            "name": "getNamespaceFromSpec",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_getNamespaceFromSpec"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003Acleanup\u0028\u0029",
            "name": "cleanup",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_cleanup"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI\\Map\u003A\u003AgenerateMapping\u0028\u0029",
            "name": "generateMapping",
            "summary": "",
            "url": "classes/Battis-OpenAPI-CLI-Map.html#method_generateMapping"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent",
            "name": "BaseComponent",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020from\u0020a\u0020JSON\u0020object\u0020response\u0020value\u0020from\u0020the\u0020SKY\u0020API",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html#method___get"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent\u003A\u003A\u0024fields",
            "name": "fields",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html#property_fields"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseComponent\u003A\u003A\u0024data",
            "name": "data",
            "summary": "JSON\u0020array\u0020of\u0020object\u0020data",
            "url": "classes/Battis-OpenAPI-Client-BaseComponent.html#property_data"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint",
            "name": "BaseEndpoint",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#method_send"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003AdecodeResponse\u0028\u0029",
            "name": "decodeResponse",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#method_decodeResponse"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#method___get"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#property_url"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A\u0024endpoints",
            "name": "endpoints",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#property_endpoints"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A\u0024api",
            "name": "api",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#property_api"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A\u0024http",
            "name": "http",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#property_http"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\BaseEndpoint\u003A\u003A\u0024EXPECTED_RESPONSE_MIMETYPE",
            "name": "EXPECTED_RESPONSE_MIMETYPE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-BaseEndpoint.html#property_EXPECTED_RESPONSE_MIMETYPE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client",
            "name": "Client",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AisReady\u0028\u0029",
            "name": "isReady",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#method_isReady"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#method_getToken"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AhandleRedirect\u0028\u0029",
            "name": "handleRedirect",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#method_handleRedirect"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003ACODE",
            "name": "CODE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#constant_CODE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003ASTATE",
            "name": "STATE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#constant_STATE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AAUTHORIZATION_CODE",
            "name": "AUTHORIZATION_CODE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#constant_AUTHORIZATION_CODE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AREFRESH_TOKEN",
            "name": "REFRESH_TOKEN",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#constant_REFRESH_TOKEN"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003AREQUEST_URI",
            "name": "REQUEST_URI",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#constant_REQUEST_URI"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003A\u0024api",
            "name": "api",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#property_api"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Client\u003A\u003A\u0024storage",
            "name": "storage",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Client.html#property_storage"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Exceptions\\ArgumentException",
            "name": "ArgumentException",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Exceptions-ArgumentException.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Exceptions\\ClientException",
            "name": "ClientException",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Exceptions-ClientException.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Mappable",
            "name": "Mappable",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-Mappable.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\TokenStorage",
            "name": "TokenStorage",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Client-TokenStorage.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\TokenStorage\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Retrieve\u0020access\u0020token\u0020from\u0020persistent\u0020storage",
            "url": "classes/Battis-OpenAPI-Client-TokenStorage.html#method_getToken"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\TokenStorage\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "Save\u0020an\u0020access\u0020token\u0020to\u0020persistent\u0020storage",
            "url": "classes/Battis-OpenAPI-Client-TokenStorage.html#method_setToken"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Component",
            "name": "Component",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Component.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Component\u003A\u003AfromSchema\u0028\u0029",
            "name": "fromSchema",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Component.html#method_fromSchema"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint",
            "name": "Endpoint",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003AfromPathItem\u0028\u0029",
            "name": "fromPathItem",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_fromPathItem"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003Ainstantiate\u0028\u0029",
            "name": "instantiate",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_instantiate"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003AmethodParameters\u0028\u0029",
            "name": "methodParameters",
            "summary": "Parse\u0020parameter\u0020information\u0020from\u0020an\u0020operation",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_methodParameters"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003AgetMethodNameForOperation\u0028\u0029",
            "name": "getMethodNameForOperation",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_getMethodNameForOperation"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003AnormalizePath\u0028\u0029",
            "name": "normalizePath",
            "summary": "Calculate\u0020a\u0020\u0022normalized\u0022\u0020path\u0020to\u0020the\u0020directory\u0020containing\u0020the\u0020class\nbased\u0020on\u0020its\u0020URL",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_normalizePath"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Endpoint\u003A\u003AmergeWith\u0028\u0029",
            "name": "mergeWith",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Endpoint.html#method_mergeWith"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\JSStyleMethod",
            "name": "JSStyleMethod",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-JSStyleMethod.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\JSStyleMethod\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-JSStyleMethod.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method\\Parameter",
            "name": "Parameter",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method-Parameter.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method\\Parameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method-Parameter.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method\\ReturnType",
            "name": "ReturnType",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method-ReturnType.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method\\ReturnType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method-ReturnType.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method",
            "name": "Method",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Method.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection",
            "name": "NamespaceCollection",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetSubnamespaceParts\u0028\u0029",
            "name": "getSubnamespaceParts",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getSubnamespaceParts"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetNamespace\u0028\u0029",
            "name": "getNamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getNamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetSubnamespaces\u0028\u0029",
            "name": "getSubnamespaces",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getSubnamespaces"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetClasses\u0028\u0029",
            "name": "getClasses",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getClasses"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AcontainsNamespace\u0028\u0029",
            "name": "containsNamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_containsNamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetClass\u0028\u0029",
            "name": "getClass",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getClass"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AgetNamespaceCollection\u0028\u0029",
            "name": "getNamespaceCollection",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_getNamespaceCollection"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#method_addClass"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003A\u0024classes",
            "name": "classes",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#property_classes"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003A\u0024subnamespaces",
            "name": "subnamespaces",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#property_subnamespaces"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\NamespaceCollection\u003A\u003A\u0024namespace",
            "name": "namespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-NamespaceCollection.html#property_namespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Property",
            "name": "Property",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Property.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Property\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Property.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Router",
            "name": "Router",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Router.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Router\u003A\u003AfromClassList\u0028\u0029",
            "name": "fromClassList",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Router.html#method_fromClassList"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Writable",
            "name": "Writable",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Writable.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Writable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Writable.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Writable\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Writable.html#method_getPath"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Writable\u003A\u003A\u0024path",
            "name": "path",
            "summary": "Relative\u0020path\u0020to\u0020class\u0020from\u0020\u0060BaseMapper\u002D\u003EgetBasePath\u0028\u0029\u0060",
            "url": "classes/Battis-OpenAPI-Generator-Classes-Writable.html#property_path"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Exceptions\\ConfigurationException",
            "name": "ConfigurationException",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Exceptions-ConfigurationException.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Exceptions\\GeneratorException",
            "name": "GeneratorException",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Exceptions-GeneratorException.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Exceptions\\SchemaException",
            "name": "SchemaException",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Exceptions-SchemaException.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper",
            "name": "BaseMapper",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003Asubnamespace\u0028\u0029",
            "name": "subnamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_subnamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003AgetSpec\u0028\u0029",
            "name": "getSpec",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_getSpec"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003AgetBaseType\u0028\u0029",
            "name": "getBaseType",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_getBaseType"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003AgetBasePath\u0028\u0029",
            "name": "getBasePath",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_getBasePath"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003AgetBaseNamespace\u0028\u0029",
            "name": "getBaseNamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_getBaseNamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_generate"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003AwriteFiles\u0028\u0029",
            "name": "writeFiles",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#method_writeFiles"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003ASPEC",
            "name": "SPEC",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#constant_SPEC"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003ABASE_PATH",
            "name": "BASE_PATH",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#constant_BASE_PATH"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003ABASE_NAMESPACE",
            "name": "BASE_NAMESPACE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#constant_BASE_NAMESPACE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003ABASE_TYPE",
            "name": "BASE_TYPE",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#constant_BASE_TYPE"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A\u0024spec",
            "name": "spec",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#property_spec"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A\u0024baseType",
            "name": "baseType",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#property_baseType"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A\u0024basePath",
            "name": "basePath",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#property_basePath"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A\u0024baseNamespace",
            "name": "baseNamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#property_baseNamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\BaseMapper\u003A\u003A\u0024classes",
            "name": "classes",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-BaseMapper.html#property_classes"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\ComponentMapper",
            "name": "ComponentMapper",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-ComponentMapper.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\ComponentMapper\u003A\u003Asubnamespace\u0028\u0029",
            "name": "subnamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-ComponentMapper.html#method_subnamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\ComponentMapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-ComponentMapper.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\ComponentMapper\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-ComponentMapper.html#method_generate"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper",
            "name": "EndpointMapper",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003AsupportedOperations\u0028\u0029",
            "name": "supportedOperations",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_supportedOperations"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003AexpectedContentType\u0028\u0029",
            "name": "expectedContentType",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_expectedContentType"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003Asubnamespace\u0028\u0029",
            "name": "subnamespace",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_subnamespace"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003ArootRouterName\u0028\u0029",
            "name": "rootRouterName",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_rootRouterName"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_generate"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers\\EndpointMapper\u003A\u003AgenerateRouters\u0028\u0029",
            "name": "generateRouters",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Mappers-EndpointMapper.html#method_generateRouters"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize",
            "name": "Sanitize",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method_getInstance"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003AisSafe\u0028\u0029",
            "name": "isSafe",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method_isSafe"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003Aclean\u0028\u0029",
            "name": "clean",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method_clean"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003Arename\u0028\u0029",
            "name": "rename",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method_rename"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003AstripHtml\u0028\u0029",
            "name": "stripHtml",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#method_stripHtml"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#property_instance"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003A\u0024reserved",
            "name": "reserved",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#property_reserved"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Sanitize\u003A\u003A\u0024htmlConverter",
            "name": "htmlConverter",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Sanitize.html#property_htmlConverter"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Specification",
            "name": "Specification",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Specification.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Specification\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Battis-OpenAPI-Generator-Specification.html#method___construct"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Specification\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Convenience\u0020method\u0020to\u0020read\u0020a\u0020variety\u0020of\u0020formats\u0020of\u0020OpenAPI\u0020spec",
            "url": "classes/Battis-OpenAPI-Generator-Specification.html#method_from"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\CLI",
            "name": "CLI",
            "summary": "",
            "url": "namespaces/battis-openapi-cli.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI",
            "name": "OpenAPI",
            "summary": "",
            "url": "namespaces/battis-openapi.html"
        },                {
            "fqsen": "\\Battis",
            "name": "Battis",
            "summary": "",
            "url": "namespaces/battis.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client",
            "name": "Client",
            "summary": "",
            "url": "namespaces/battis-openapi-client.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Client\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/battis-openapi-client-exceptions.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes",
            "name": "Classes",
            "summary": "",
            "url": "namespaces/battis-openapi-generator-classes.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Classes\\Method",
            "name": "Method",
            "summary": "",
            "url": "namespaces/battis-openapi-generator-classes-method.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/battis-openapi-generator-exceptions.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator\\Mappers",
            "name": "Mappers",
            "summary": "",
            "url": "namespaces/battis-openapi-generator-mappers.html"
        },                {
            "fqsen": "\\Battis\\OpenAPI\\Generator",
            "name": "Generator",
            "summary": "",
            "url": "namespaces/battis-openapi-generator.html"
        }            ]
);
